### ISSUE TITLE
TEL2022010 - Area update

### ISSUE THREAD

**Issue by emberleyj** [PopulationEcologyDivision/andesmerge#19]
Set 111 Area 523
Set 120 Area 524
Set 123 Area 524
Set 125 Area 524
Set 127 Area 523
Set 129 Area 524
Set 131 Area 523

**Comment by MMMcMahon** [comment]
added some functionality that automatically determines the NAFO area and assigns the correct AREA to sets.  The area value for 523 and 524 was blank, so nothing got assigned.  Fixed
