### ISSUE TITLE
TEL2022010 - Set 99

### ISSUE THREAD

**Issue by emberleyj** [PopulationEcologyDivision/andesmerge#20]
Set 99 - DIST should be 1.61 and SPEED should be 3.22

**Comment by MMMcMahon** [comment]
done

**Comment by emberleyj** [comment]
sorry, this should have said set 141.  But from the great examples you gave, maybe the entry was just entered as is

**Comment by MMMcMahon** [comment]
set 141 was set to the specified values

**Comment by emberleyj** [comment]
The original error here with the distance and speed for set 99 in TEL2022010 has not been corrected
