### ISSUE TITLE
TEL2022010 Set 148 - were comments cut short?

### ISSUE THREAD

**Issue by emberleyj** [PopulationEcologyDivision/andesmerge#21]

**Comment by MMMcMahon** [comment]
No - the full comment is :

> Press winch button to quick. Manually change time and position stamp to match data logger. Time was 10:43 position 42 27.707N 064 51.821W

I think the comments field for sets can be up to 2000 characters long, which is pretty long - here's and example:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc auctor mattis erat iaculis suscipit. Pellentesque semper fermentum ex sit amet tincidunt. Nunc ut condimentum lorem. Sed aliquam egestas orci, id elementum arcu pharetra quis. Etiam vestibulum velit et mi convallis fermentum. Morbi pellentesque, lectus at condimentum suscipit, lectus metus vulputate nibh, sit amet fermentum nunc libero eu nibh. Nunc sagittis, nunc non placerat viverra, nisi sapien fermentum mi, pellentesque viverra arcu orci vel quam. Aliquam erat volutpat.

Vivamus lobortis venenatis purus quis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam sem nunc, finibus sit amet fermentum vel, lacinia nec risus. Sed fermentum quam ligula, sed laoreet dolor porttitor et. Suspendisse potenti. Etiam sit amet lectus convallis, mattis erat ut, elementum turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam velit est, interdum at ex ut, auctor tempor felis. Nam suscipit sagittis turpis et eleifend. Sed sapien erat, tempus porttitor est eget, fringilla feugiat urna. Sed auctor magna ipsum, in consequat libero auctor ut.

Morbi quis semper magna, non cursus purus. Aenean sagittis ex ut magna varius congue. Praesent lacus quam, facilisis vitae tellus sit amet, iaculis bibendum nunc. Fusce bibendum diam magna, a fringilla libero malesuada ut. Vivamus venenatis neque sed accumsan ornare. Phasellus urna nisi, molestie et hendrerit id, consectetur quis est. Donec id tincidunt justo.

Nulla ornare rhoncus mauris, eget varius ante pulvinar eget. Curabitur iaculis tellus feugiat rhoncus porttitor. Duis eu nisl at ipsum ultrices porta. Quisque sit amet elit nisl. Vestibulum et viverra mauris. Vivamus iaculis sapien varius lorem porta, sit amet suscipit orci aliquet. Sed quis bibendum enim. Suspendisse potenti. Praesent sodales volutpat diam a ultricies. Quisque at scelerisque lorem. Quisque efficitur nisl at nisl imperdiet, ac lacinia tortor nec.

**Comment by emberleyj** [comment]
sorry, this should have said set 141. But from the great examples you gave, maybe the entry was just entered as is
