### ISSUE TITLE
TEL2022010  Several sets do not have a size class in ANDESE_CATCHES but they don't exist in ANDESE_BASKETS

### ISSUE THREAD

**Issue by emberleyj** [PopulationEcologyDivision/andesmerge#23]
Could these be ghost records from trying different species codes but not making a full entry for that species?  It appears that they do not have a catch weight associated with them and can likely be deleted unless you see something more in the ANDESE files

**Comment by MMMcMahon** [comment]
You were correct - I had a bad 'merge' that was appending needless records.  I've made the correction.  Thanks!
